[package]
name = "ralph-doria/project-rf-demo"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Trove = "sleitnick/trove@1.5.0"
RobloxStateMachine = "prooheckcp/robloxstatemachine@>0.0.0, <10.0.0"
Promise = "evaera/promise@4.0.0"
GoodSignal = "stravant/goodsignal@0.2.1"
RaycastHitbox = "ruizukun-dev/raycasthitbox@1.0.2"
CameraShaker = "brittonfischer/camerashaker@0.1.0"
Spring = "brittonfischer/spring@0.1.0"
react = "jsdotlua/react@17.1.0"
react-roblox = "jsdotlua/react-roblox@17.1.0"
TopBarPlus = "legitatx/topbarplus@3.0.5"