local Shared = require("./Components/SharedReceiver")
local Consumable = require("./Components/ConsumableReceiver")
local Gun = require("./Components/GunReceiver")
local Melee = require("./Components/MeleeReceiver")
local Wearable = require("./Components/WearableReceiver")
local Stackable = require("./Components/StackableReceiver")

Shared()
Consumable()
Gun()
Melee()
Wearable()
Stackable()