local Shared = require("./Components/SharedReceiver")
local Consumable = require("./Components/ConsumableReceiver")
local Gun = require("./Components/GunReceiver")
local Melee = require("./Components/MeleeReceiver")
local Wearable = require("./Components/WearableReceiver")

Shared()
Consumable()
Gun()
Melee()
Wearable()